on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:

name: build-deploy-to-cdn
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: set package.json version
        uses: menduz/oddish-action@master
        with:
          deterministic-snapshot: true
          only-update-versions: true

      - id: install
        name: install
        run: npm ci

      - name: build
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
        run: npm run build-prefix

      - name: test
        run: npm run test
        
      - name: copy package.json
        run: cp "./package.json" "./public/package.json"

      - name: publish npm package
        uses: menduz/oddish-action@master
        with:
          scope: "@dcl"
          access: public
          cwd: './public'


          ## use action runId instead of current date to generate snapshot numbers
          deterministic-snapshot: true

          ## inform gitlab after publishing to proceed with CDN propagation and rollouts
          # 104 == https://dcl.tools/pipelines/static-sites-pipeline
          gitlab-pipeline-url: ${{ secrets.GITLAB_CDN_DEPLOYER_URL }}
          gitlab-token: ${{ secrets.GITLAB_CDN_DEPLOYER_TOKEN }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
